services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - ENV_FILE=chuchutree/.env.production
    image: chuchu-frontend-dev:latest
    container_name: chuchu-frontend-dev
    network_mode: host 
    environment:
      - NODE_ENV=development
      - PORT=3334
      - HOSTNAME=0.0.0.0
    command: ["node", "server.js"] 
    restart: unless-stopped