services:
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - ENV_FILE=chuchutree/.env.production
    image: chuchu-frontend-prod:latest
    container_name: chuchu-frontend-prod
    network_mode: host 
    environment:
      - NODE_ENV=development
      - PORT=3333
      - HOSTNAME=0.0.0.0
    command: ["node", "server.js", "--port", "3333"] 
    restart: unless-stopped